### ISSUE TITLE
Add dask.org/survey redirect

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask.github.io#13]
It would be nice to have a url under dask.org, something like dask.org/survey, that re-directs to the [user survey](https://docs.google.com/forms/d/e/1FAIpQLSeG12dOna6dIR85Qza6Cr_CZ9rxqH08pilmeQR7ehaJDu25Fw/viewform). Not sure if it's straightforward to do such a re-direct on the server. cc @aterrel

We could also add javascript similar to the http -> https redirect in https://github.com/dask/dask-sphinx-theme/pull/12

**Comment by TomAugspurger** [comment]
I think we can add a survey.html file with a redirect.


________________________________
