### ISSUE TITLE
Anaconda logo is missing

### ISSUE THREAD

**Issue by mrocklin** [dask/dask.github.io#3]
On the front page of dask.org we are pointing to an Anaconda Logo that is no longer on the web.  What is a good long-term stable link that we can use?

cc @jcrist @seibert

**Comment by mrocklin** [comment]
We used to use 

https://github.com/dask/dask.github.io/blob/197ff92e1660aa04885843d3cf4fe131e99d72cf/index.html#L203

**Comment by martindurant** [comment]
Marketing suggests https://live-2018anaconda.pantheonsite.io/wp-content/uploads/2018/06/Anaconda_horizontal_RGB.png

**Comment by mrocklin** [comment]
White or transparent background would be best if possible.

**Comment by mrocklin** [comment]
Also, can we assume that this link will remain valid for a few years?

**Comment by martindurant** [comment]
"I'm not sure how long our current website iteration will be around." - hold on, I'll see if I can tease out something more permanent

**Comment by mrocklin** [comment]
We can always just download something and keep it here if necessary.

**Comment by martindurant** [comment]
That choice I don't know about; the link I provided is the best I have actually from corporate sources, but there's https://en.wikipedia.org/wiki/Anaconda_(Python_distribution)#/media/File:Anaconda_Logo.png on wikipedia, sure to be around.

**Comment by martindurant** [comment]
Sorry, https://upload.wikimedia.org/wikipedia/en/c/cd/Anaconda_Logo.png

**Comment by mrocklin** [comment]
Grand.  Thanks for tracking that down Martin
