### ISSUE TITLE
Adding DataPrep to "Powered by Dask"

### ISSUE THREAD

**Issue by dovahcrow** [dask/dask.github.io#31]
Hi team, our new library, DataPrep (https://github.com/sfu-db/dataprep), is using Dask for its execution engine. Is there any chance that we can be listed under the "Powered by Dask" section on "https://dask.org/"?

DataPrep is a library that lets data scientists prepare the data using a single library with a few lines of code. One of its modules, DataPrep.eda uses Dask extensively as its execution engine for calculating the statistics and data for charts.

**Comment by jsignell** [comment]
Thanks for opening this! I think we would be happy to add DataPrep to the list. I am not sure if there is some process though. @dask/maintenance

**Comment by TomAugspurger** [comment]
There isn't a process that I'm aware of. I'm happy with something informal, like open a PR / issue and wait a day or so for someone to object.

@dovahcrow would you be interested in submitting a pull request adding DataPrep? I think it'd be good to add it just before the projects without logos.

**Comment by dovahcrow** [comment]
Hi @TomAugspurger I just create the PR #32. Please let me know if you have any comments.
