### ISSUE TITLE
anchor supported by section

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask.github.io#40]
Currently the way to go to the supported by section is to go https://dask.org/ then scroll to the bottom.

A hyperlink to this section would be beneficial and perhaps hyperlinks to the other sections e.g. Powered by dask.

**Comment by martindurant** [comment]
Definitely I support adding anchors to the page, so we can jump to them. I can't think of an obvious place to *display* these, though - but perhaps that isn't the request.

**Comment by jrbourbeau** [comment]
+1 nice suggestion @raybellwaves! I think adding an `id=` and corresponding link should provide a way to link to specific sections of the dask.org landing page. For example:

```diff
diff --git a/index.html b/index.html
index 37386ef..0824383 100644
--- a/index.html
+++ b/index.html
@@ -217,7 +217,7 @@ lr.fit(train, test)</code></pre>

             <div class="row">
               <div class="col-md-12">
-                <h2 class="featurette-heading">Powered by Dask</h2>
+                <h2 class="featurette-heading" id="powered-by"><a href="#powered-by">Powered by Dask</a></h2>
                 <p class="lead">
                 These software projects are well-integrated with Dask,
                 or use Dask to power components of their infrastructure.</>
```

**Comment by jsignell** [comment]
>I can't think of an obvious place to display these, though - but perhaps that isn't the request.

Yeah probably it's more useful for external pages to include in links - doesn't need to be displayed on the page itself.

**Comment by raybellwaves** [comment]
Thanks for the discussion. I think I meant anchor instead of hyperlink. Yes hyperlink to that section from outside of that page.
