### ISSUE TITLE
Add a one-click Dask google calendar link

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask.github.io#50]
I've always found it super awkward to get the information from the Dask calendar on this page (https://docs.dask.org/en/latest/support.html) into my actual calendar. Perhaps adding this link to the webpage will make that easier for people: https://calendar.google.com/calendar/u/0?cid=NGwwdnRzMGMxY2dkYnE1amhjb2dqNTVzZnNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by mrocklin** [comment]
Sounds fine to me.  The source for that page is here:
https://github.com/dask/dask/blob/main/docs/source/support.rst

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/7733
