### ISSUE TITLE
docs website is down

### ISSUE THREAD

**Issue by ntabris** [dask/dask.github.io#57]
docs.dask.org is returning 403

<img width="286" alt="image" src="https://user-images.githubusercontent.com/46289310/197836943-1495c5c9-6ded-4ba5-9ca7-68cc7b288da9.png">

**Comment by ntabris** [comment]
seems to be working again, I guess this was CDN blip or something

**Comment by ntabris** [comment]
Or maybe this is still an issue. Some pages appear to be working, some are still giving me 403's...

```bash
~ curl --head "https://docs.dask.org/en/latest/"
HTTP/2 403
date: Tue, 25 Oct 2022 17:10:35 GMT
content-type: text/html
content-length: 173
cf-cache-status: EXPIRED
server: cloudflare
cf-ray: 75fc9108bb068e9f-DEN
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by jrbourbeau** [comment]
Thanks for reporting @ntabris. FWIW I just did some random clicking around the `stable` and `latest` version of the docs and all pages loaded (though I only click around ~10 times each). cc @jacobtomlinson @quasiben who have knowledge about Dask docs hosting

**Comment by ntabris** [comment]
I'm no longer finding pages that give me error. Seems like a CDN related issue, I don't know anything about how dask docs are hosted though other than the fact that this was 403 from cloudflare.

**Comment by jrbourbeau** [comment]
Okay, glad to hear you're no longer seeing errors. I'm going to close this issue out for the time being. Jacob / Ben let us know if there's any additional actions you think we should take, or if this was most likely just some transient CDN thing

**Comment by jacobtomlinson** [comment]
Following up a couple of days later to say this hasn't been reported elsewhere and things are working fine for me. Must've been a transient hosting issue that is resolved now.

**Comment by jrbourbeau** [comment]
Thanks for following up @jacobtomlinson
